### ISSUE TITLE
SDL_CreateWindow failed on GLX visual

### ISSUE THREAD

**Issue by Eonfge** [etlegacy/etlegacy#1732] opened 2021-09-22 09:26 UTC
Possibly a duplicate of; https://github.com/etlegacy/etlegacy/issues/886 although that issue is rather stale

I discovered an issue with ET:Legacy, on a laptop with Linux. The situation is as followed:

- Starting the application normally works 
- Starting the application with 'Launch with Discrete GPU' gives an error

The Laptop has an NVidia card, but that one is not enabled by default. If I want to run an application with graphics, I have to right-click and tell the laptop to use this extra hardware. Now, this works with some applications like GZDoom but with ET:Legacy I get an error.

### Attachments
- [crashlog.txt](https://github.com/etlegacy/etlegacy/files/7209442/crashlog.txt)
- [inxi.txt](https://github.com/etlegacy/etlegacy/files/7209448/inxi.txt)

**Comment by rmarquis** [comment] 2021-09-22 09:34
Could be related to #1639 (also prime related), though the error seems different.

**Comment by rmarquis** [comment] 2021-09-22 11:58
A quick look around the Internet suggests that multisampling support (`SDL_GL_MULTISAMPLESAMPLES`) might be problematic.

Could you try to:
* launch the game on your Intel card
* set `r_ext_multisample` to 0
* exit and relaunch the game on the nvidia card

**Comment by Eonfge** [comment] 2021-09-22 12:38
Can confirm. This workaround fixes the issue for me. Setting it back to 4 re-introduces the crash, so it's 100% reproducible now.

**Comment by rmarquis** [comment] 2021-09-22 12:40
Thank for feedback. Now that we know what the issue is, we can think of a proper fix.

**Comment by Eonfge** [comment] 2021-10-04 15:03
This issue is fixed! With the latest version of ETL sporting SDL 2.0.16, I can no longer reproduce this issue at the office. I'm not sure if we should close this issue since there were also other people reporting similar issues, but I consider it fixed.

**Comment by rmarquis** [comment] 2021-10-04 15:06
That sounds good! It might also have been fixed by a new driver version.
Let's ask for more feedback before closing.

**Closed as completed** 2021-12-09 17:17 UTC
Labels: 🐞 Bug, ❓ Feedback, P3: Normal, cat: client
