### ISSUE TITLE
Crashing on windows 10

### ISSUE THREAD

**Issue by teixeiras** [etlegacy/etlegacy#1615] opened 2021-03-08 09:59 UTC
Hi I need help fetching logs on windows 10.

Whenever I launch the etl, it appears the initial screen to select user definitions, but crash immediately without any user interaction. Where I can get the logs?

**Comment by rafal1137** [comment] 2021-03-08 10:19
Its called Event Viewer in Windows. If you find something related to etl. Feel free to post it here so we can take a look at it.

**Comment by rmarquis** [comment] 2021-03-08 10:36
In addition, have a look at the `<User>/Documents/ETLegacy` folder. Some output might have been caught before the app crashed.

**Comment by teixeiras** [comment] 2021-03-08 11:31
https://we.tl/t-mb8BrhVr3O

On documents folder there isn't anything, neither on windows events :| this is really wierd

**Comment by isRyven** [comment] 2021-03-08 11:42
Try running the shortcut with dev log arguments: `+set logfile 2 +set developer 1`, this will create `etconsole.log` in `Documents/ETLegacy/legacy` folder, at least it can help to pinpoint the area where the segment violation could happen. Also event logger won't contain anything probably because of graceful shutdown? Nice theme btw.

**Comment by teixeiras** [comment] 2021-03-08 14:46
I think it will not help a lot :P 

File content:
       0 logfile opened on Mon Mar 08 14:44:20 2021
       0 SDL input devices shut down.
       0 Network shutdown

**Comment by rafal1137** [comment] 2021-03-08 14:50
Can you download latest snapshot from here: https://www.etlegacy.com/workflow-files/
And try to run it ?

**Comment by isRyven** [comment] 2021-03-08 16:05
Does this only affect 2.77? Or 2.76 also crashes for you?

**Comment by Aranud** [comment] 2021-04-28 07:38
@teixeiras Do you still have the issue ?

**Comment by Aranud** [comment] 2021-08-01 21:04
Closing for now. If the issue is still present, don't hesitate to reopen the ticket.

**Closed as completed by Aranud** 2021-08-01 21:04 UTC
