### ISSUE TITLE
v. 2.76.810.g164b964c3-1 crashes just before entering a map

### ISSUE THREAD

**Issue by Chhkuot** [etlegacy/etlegacy#1527] opened 2020-11-22 07:12 UTC
Manjaro Linux, [system_information.txt](https://github.com/etlegacy/etlegacy/files/5579095/system_information.txt)

Build from AUR package git version etlegacy-git 2.76.810.g164b964c3-1 [https://aur.archlinux.org/packages/etlegacy-git/](https://aur.archlinux.org/packages/etlegacy-git/)

Works fine: Launching the game, creating a profile, configuring the settings, displaying the servers list, joining a server.

Crash occur at the screen with the Europe map on the left side and server connection informations on the right side, after missing maps have been downloaded, at the moment where the game session should start.

Launching the game with the terminal command `$ etl` give this output [etlegacy_terminal_output.txt](https://github.com/etlegacy/etlegacy/files/5579097/etlegacy_terminal_output.txt).

**Comment by isRyven** [comment] 2020-11-22 09:26
Duplicate of https://github.com/etlegacy/etlegacy/issues/1443.

I suggest installing etl 32bit version (from the website) if you want to play on 2.76 servers.
Currently only official and one custom server (https://et.trackbase.net/server/45410) supports patched binary.

**Closed as completed** 2020-11-22 15:36 UTC
Labels: ❌ Duplicate

**Comment by Chhkuot** [comment] 2020-11-23 01:13
Sorry about the duplicate. Thanks for the server information.
