### ISSUE TITLE
Directional sound issue with SDL2 backend

### ISSUE THREAD

**Issue by BystryPL** [etlegacy/etlegacy#1806] opened 2021-11-03 19:44 UTC
From user "Abject" on ET: Legacy Competitive Discord server:

> Hey,
> 
> is SDL2 sound expected to be default? I've been playing few games so far and every time I was so confused with things being right next to me. Today I find out about SDL and OPENal settings and second one feels way more normal.
> SDL2
> https://streamable.com/csr3ef
> OPENAL
> https://streamable.com/1wualx
> 
> btw. could you please let me know what is the command for this settings? I want to set openal permanent for now.
>

**Comment by rmarquis** [comment] 2021-11-03 20:23
OpenAL used to be the default, but SDL2 has been reverted back as the default sound system in 2.78.0, as OpenAL has some issues in a few specific cases (some environmental audio too loud).

There might be some subjectivity here, but I also find OpenAL better for gameplay (more "natural" and immersive, and easier to evaluate distance of noise sources compared to SDL which sounds "flat"). OpenAL also has surround sound support, and a few bugfixes related to OpenAL were applied in 2.78.0 too.

The cvar is `s_initsound` , available in `Options > Settings > Audio > Sound system`.

Closing because that's not really an issue.

**Comment by Aciz** [comment] 2021-11-03 20:24
Ummh, what? There's clearly an issue here, the guy is throwing a grenade in front of him, yet the explosion comes from the left?

**Comment by rmarquis** [comment] 2021-11-03 20:26
Sorry, thought he just wanted OpenAL back. I didn't actually watched the video, my bad (long story short, no sound on my machine right now because driver update).

**Comment by Aciz** [comment] 2021-11-03 20:41
Another example, metal impact sound playing on the right with SDL2 when shooting a surface in front of me.

SDL2:
https://streamable.com/8fexha

OpenAL:
https://streamable.com/750bjm

**Comment by Aciz** [comment] 2021-11-03 20:52
Seems like it's always playing some sounds as if they are coming from East.

https://streamable.com/lyya28

Edit: this is the case in the Ice clip in the starting post as well.

**Comment by rmarquis** [comment] 2021-11-03 21:01
Is this happening on Windows, or Linux? (just to rule out SDL 2.0.14/16).

**Comment by Aciz** [comment] 2021-11-03 21:02
Windows for me, so 2.0.14.

**Comment by Aciz** [comment] 2021-11-03 21:06
Eh, the clips are actually from 2.0.16, as I tested with my mapping installation which I haven't updated yet (running 2.78.0), so that is actually 2.0.16. But, it does happen with 2.78.1 too, so 2.0.14 is also affected.

**Comment by rmarquis** [comment] 2021-11-04 13:44
All right, fixed my sound drivers.

I must say it's quite hard to say the sound is buggy for me (I've a standard cheap stereo headphone, nothing fancy). Not that there might not be an issue here, but I always attributed the better OpenAL sound to the SDL lack of directional sound support, if that makes sense.

With SDL2 backend enabled, could you check if:
* disabling the doppler effect helps? (in UI settings) (see commits in #22, and more "recently" 5051da8c3849358f3169600795d55ae4e8d783f3)
* disabling system spatial sounds helps? (Windows Sonic, Dolby Access, DTS...)

**Comment by randomek** [comment] 2021-11-04 23:24
Today I join from Client Linux 78.0 to 78.1 server (etlegacy on TM) and my sound was very buggy like 2-3 seconds lags (default it was SDL2). I changed it to OpenAL but it was worse. I upgraded client to 78.1 and on OpenAL sounds was without lags but were very strange for me. Changed to SDL2 and it works good. When server was 78.0 I didn't have any problem with sound (from 78.0 Linux client).

**Comment by rmarquis** [comment] 2021-11-05 08:11
Unless you can constantly reproduce it, this is most likely completely unrelated. There hasn't been any single change in sound code (nor client nor mod side) in 2.78.1 afaik.

**Comment by Aciz** [comment] 2021-11-05 08:21
Tested without doppler effect, no difference. I also don't have any spatial audio enabled on my system on OS level.

**Comment by rmarquis** [comment] 2021-11-05 13:06
I tested 2.77.1 and 2.76. The issue is the same with SDL backend, so at least it doesn't seem to be a regression.
Maybe there is something to fix here, but I'd honestly blame SDL for its lack of 3D sound support.

**Comment by BystryPL** [comment] 2021-11-11 17:03
Another example of some directional sound issues with SDL2: https://www.twitch.tv/bobiika/clip/ChillyEnthusiasticShallotGivePLZ-zNTMKBIxMYOUh93O?filter=clips&range=7d&sort=time

**Comment by jackeri** [comment] 2021-11-11 17:20
Can we have a demo of that? Might be useful if it happens in the demo as well..

**Comment by BystryPL** [comment] 2021-11-11 17:40
> Can we have a demo of that? Might be useful if it happens in the demo as well..

That person didn't record the demo sadly.

**Comment by jackeri** [comment] 2021-11-11 17:42
If this happens in the future with such a clear case a demo file should be checked and uploaded if the issue is duplicated on it.

**Closed as completed** 2021-11-15 16:44 UTC
Labels: 🐞 Bug, P3: Normal, cat: client
