### ISSUE TITLE
ETL v2.81.0-x86_64 (Linux) does not have SDL Wayland driver built in

### ISSUE THREAD

**Issue by kaixiong** [etlegacy/etlegacy#2245] opened 2023-02-03 21:49 UTC
Hi, I just installed and ran the ETL v2.81.0-x86_64 and noticed that Wayland is not supported by the builtin SDL:

```
       0 ^2ET Legacy v2.81.0 linux-x86_64 Jan 27 2023
       0 Zone megs: 64
       0 INFO: fs_game now defaults to 'legacy' mod instead of 'etmain'
       ...
       0 ----- Initializing Renderer ----
       0 SDL build version 2.24.1 - link version 2.24.1
       0 SDL_Init(SDL_INIT_VIDEO) FAILED (wayland not available)
       0 SDL_Init(SDL_INIT_VIDEO) FAILED (wayland not available)
       0 Setting r_mode -2 failed, falling back on r_mode 4
       0 SDL_Init(SDL_INIT_VIDEO) FAILED (wayland not available)
       0 ----- Client Shutdown ----------
```

Note that I force SDL to use Wayland with `SDL_VIDEODRIVER=wayland`. I've been doing this for a while now on ETL v2.80.x without issues. Currently using Pop_OS! 22.04, with GNOME Shell 42.3.1 on an AMD RX 6900XT card.

**Comment by rafal1137** [comment] 2023-02-03 22:30
Thats weird indeed since it was added since 2021 by @jackeri 
https://github.com/etlegacy/etlegacy-libs/commit/61917d6fa520c2278b46bff053c7bd2f39176106

PS: But as always something could broke

**Comment by ActiumDev** [comment] 2023-03-10 22:09
I have the exact same issue. Regression from 2.80.2, which used to and still works. What solves it with 2.81.0 for me is running etl with Debian Sid's native SDL lib instead of the one shipped with etl via: `SDL_DYNAMIC_API="/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0" ./etl.x86_64`

Resulting output:

```
       0 ----- Initializing Renderer ----
       0 SDL build version 2.24.1 - link version 2.26.3
       0 SDL initialized driver "wayland"
       0 Initializing OpenGL display
```

**Comment by jackeri** [comment] 2023-03-13 08:23
This should have been fixed with the release of 2.81.1, please confirm.

**Comment by Eonfge** [comment] 2023-03-13 15:52
Currently preparing a version of ETL with Wayland by default:
https://github.com/flathub/com.etlegacy.ETLegacy/pull/28

It works for me, but if some people can confirm it working as well, that would be great.

## Edit
Log of my full success, giving you also a glimps at debug statements.
[wayland-log.txt](https://github.com/etlegacy/etlegacy/files/10959227/wayland-log.txt)

I did have a screen full of graphical artifacts as the game started, but after that everything worked and I could join a game.

**Comment by ActiumDev** [comment] 2023-03-13 18:46
> This should have been fixed with the release of 2.81.1, please confirm.

I can confirm that this fixed the issue. Tried with the 64-bit binaries.

**Comment by jackeri** [comment] 2023-03-13 19:49
Thank you all for the feedback. Closing the issue then.

**Closed as completed by jackeri** 2023-03-13 19:49 UTC
Labels: 🐞 Bug, P3: Normal, cat: client

**Comment by Eonfge** [comment] 2023-03-13 21:43
Sounds good, I'll release the Wayland-enabled version through Flathub.
