### ISSUE TITLE
Sometimes cannot vote for next map during intermission time on Silent mod servers

### ISSUE THREAD

**Issue by jori-be** [etlegacy/etlegacy#1454] opened 2020-05-09 20:31 UTC
Lately I've installed ET legacy 2.76 and I've noticed that sometimes I cannot vote for the next map during intermission time on Silent mod servers.

Before I was using ET legacy 2.75 and I never seen that kind of issue.
Few people using ET legacy 2.76 confirmed this behavior so far.

For me the problem is like 33% reproducible. 

Uploaded video to wetransfer, find link below because file is too big for the forum. (only available for 6 days)

https://we.tl/t-JmqNJCKeWH

**Comment by rmarquis** [comment] 2020-05-10 10:49
Duplicate of #1406. Closing.

**Closed as completed by rmarquis** 2020-05-10 10:49 UTC
Labels: 🐞 Bug, ❌ Duplicate, P3: Normal, cat: general
