### ISSUE TITLE
KP_STAR bind discrepancy with vanilla game

### ISSUE THREAD

**Issue by ensiform** [etlegacy/etlegacy#1516] opened 2020-10-26 12:58 UTC
In the SDL port which came from ioquake3, the '*' on keypad was changed from the literal '*' bind to KP_STAR.

In both Quake III Arena and Wolf: ET vanilla games, this is a regression except in the mac ports. The bind was never used as KP_STAR in Linux or Windows.

Relevant change was made in this commit here to bring back vanilla parity:

https://github.com/etfdevs/ETe/commit/cd33d835d972d248d82367f9120c52687c813d46#diff-456bceca60ccfd220eca680ae0bb67cbbf11970126078e52977a937f7e2bd34aR307

**Comment by ensiform** [comment] 2020-10-26 12:58
There was recent discussion on Discord about this bind being an issue, figured I would add this here.

**Comment by rmarquis** [comment] 2020-10-27 08:30
Why is this an issue, if I may ask?

**Comment by ensiform** [comment] 2020-10-27 11:44
A regression in people's binds/configs.

**Comment by rmarquis** [comment] 2020-10-27 11:56
People shouldn't use their old config. Unless there is a real issue, I'd close this as "invalid".

**Comment by ensiform** [comment] 2020-10-27 12:44
Nowhere did I imply reusing the autogenerated config. 🙄

Many players use external executed configs for binds and such.

**Comment by rmarquis** [comment] 2020-10-27 13:00
Great. As the risk to sound like an ass, if reusing configs created for vanilla engine isn't the issue, then what *is* the actual issue? Could you actually describe the regression?

**Comment by ryzyk-krzysiek** [comment] 2020-10-27 13:49
I guess I can give an example as I was the person having a problem with KP_STAR.

I had a bind for increasing/lowering gamma and I used "\*" and "-" on keypad as binds for it. I made it while using vanilla ET sometime ago and copied it to my ETLegacy config but never used it for quite a while as I didn't play it. The bind worked fine in vanilla, but over the weekend as I was doing some other scripts but this time in ETLegacy client because it was more convenient for me I realized that script for gamma isn't working. To be precise, the "\*" bind didn't despite that when I did "/bind *" it showed that it is set correctly.

It took me some time and a post on discord to realize as to why it is not working in ETLegacy. Eventually I fixed it myself as I went to options and set something random to "*" to see that it registers as "KP_STAR".

**Comment by Aciz** [comment] 2020-10-27 16:39
> Great. As the risk to sound like an ass, if reusing configs created for vanilla engine isn't the issue, then what _is_ the actual issue? Could you actually describe the regression?

Well for instance, different keyboard layout have the non-numpad * in different places. Finnish keyboard layout for example has a dedicated key for it next to enter. Both and bindable as seperate binds, one with * and one with KP_STAR. 

![Screenshot_20201027-183524__01__01](https://user-images.githubusercontent.com/14221121/97332962-b4eac800-1883-11eb-80e0-02c4ee790d0f.jpg)

**Comment by rmarquis** [comment] 2020-10-27 18:20
Yes, which is the reason these two scancodes are separated in the first place (`SDLK_ASTERISK` and `SDLK_KP_MULTIPLY`).
What am I missing here? Sounds like yet-another-old-config-reuse user case, and that the current situation is better.

**Comment by isRyven** [comment] 2020-10-27 18:31
Do i understand it correctly that you propose to revert it to regressive behavior?

**Comment by ensiform** [comment] 2020-10-27 19:15
Further looking at original source shows that the original client always used the asterisk char mapping Across all language maptokey lists in win_wndproc regardless of keypad or not. KP STAR was always a dead bind.

**Comment by Aciz** [comment] 2020-10-27 19:38
> Yes, which is the reason these two scancodes are separated in the first place (`SDLK_ASTERISK` and `SDLK_KP_MULTIPLY`).
> What am I missing here? Sounds like yet-another-old-config-reuse user case, and that the current situation is better.

Point being, you lose one bindable key if both are treated as KP_STAR, or did I understand this correctly?

**Comment by rmarquis** [comment] 2020-10-27 21:06
The opposite. `K_KP_STAR` is the internal equivalent to the SDL constant `SDLK_KP_MULTIPLY` (numpad), and `*` would be `SDLK_ASTERISK` (alphanumeric).

Current behaviour in master is that both keys are recognized as _different_ keys, which wasn't apparently the case in the original client (which is nothing more than a clusterfuck of harcoding for a few selected mapping).
The proposed change is to make numpad `*` (`SDLK_KP_MULTIPLY`) be recognized as alphanumeric `*` (`SDLK_ASTERISK`) and effectively _losing_ one bind.

There is indeed a bind discrepancy with vanilla client, but that is because the original issue has been fixed a long time ago.

**Closed as completed** 2020-10-27 23:38 UTC
Labels: ❌ Invalid
