### ISSUE TITLE
Certain objects invisible with cg_simpleItems 1

### ISSUE THREAD

**Issue by timosmit** [etlegacy/etlegacy#1448] opened 2020-05-06 16:47 UTC
Since the last snapshot (v2.76-1075-g765ea79), weapons, objectives and medic kits/ammo crates re reported to not be drawn when using `cg_simpleItems 1`. This appears to be a regression since the previous snapshot (v2.76-1002-g588e294).

Attached is a screenshot sent by <=TM=>eMMiel. The objective should be on the table, but clearly is not.

![no_objective](https://user-images.githubusercontent.com/4281972/81204746-f764d380-8fc9-11ea-97ae-a680b634a933.png)

**Comment by timosmit** [comment] 2020-05-06 17:00
This seems to be related to recent changes with regards to #1290.

**Comment by rmarquis** [comment] 2020-05-06 17:12
What's the map here?

I feel this is more related to the sinking items object (stuttering/collision boxes), rather than `cg_simpleItems` rework. The last relevant commit of simpleItem is dated from March 1, but build 1002 wasn't affected (shipped on March 19).

**Comment by timosmit** [comment] 2020-05-06 17:14
This is `snatch3`.

**Comment by rmarquis** [comment] 2020-05-10 21:24
Cannot reproduce. Objective and ammo/health crates are visible with both `cg_simpleItems 0` and `1`, on latest master.

**Comment by isRyven** [comment] 2020-05-11 07:18
I have received demos, but i didn't have time yet to watch it.

**Comment by isRyven** [comment] 2020-05-11 07:50
I have watched demos, and can't reproduce the bug locally, neither on master or 1075 revision. But it's clearly not the server-side issue. Could be related to 3cfe9bba92548a76a825e7c6aaf7c74cf4488b47.
[2020-05-06-182525-snatch3.zip](https://github.com/etlegacy/etlegacy/files/4608200/2020-05-06-182525-snatch3.zip)

**Comment by timosmit** [comment] 2020-05-11 07:53
This should be reproducible by playing on the TeamMuppet server.

**Comment by rmarquis** [comment] 2020-05-12 15:59
Confirmed on TM server, with 32 players (if that is any relevant).
Build 1075 is indeed fine locally.

**Comment by rmarquis** [comment] 2020-05-29 11:59
I could reproduce on 1075, but only on a MSVC build. This has been fixed in 2db96c9a00dca1174c9a9d19b8ab32c4116085d6.

**Closed as completed by rmarquis** 2020-05-29 11:59 UTC
Labels: 🐞 Bug, P1: Urgent, cat: mod CGAME
