### ISSUE TITLE
ui.mp.x86_64.so: undefined symbol: __acosf_finite

### ISSUE THREAD

**Issue by rayksland** [etlegacy/etlegacy#1484] opened 2020-05-24 15:34 UTC
Upgraded to Ubuntu 20.04 LTS from 18.04

etl crashes on start with the following:

Sys_LoadDll(/home/ray/.etlegacy/legacy/ui.mp.x86_64.so)...        0 failed: /home/ray/.etlegacy/legacy/ui.mp.x86_64.so: undefined symbol: __acosf_finite

compiled from git and installed -- etl successfully launches

connect to favourite server sends -- "updated" etl_bin_v2.76.pk3 overwrites compiled ui.mp.x86_64.so

etl crashes with previous error.

--notes: etl falsely detects git compiled version as "out-dated!"

**Comment by rmarquis** [comment] 2020-05-24 15:38
Duplicate of #1443.

The issue has been fixed in master, but you'll either need to compile or wait for the next pre-compiled build.

**Closed as completed by rmarquis** 2020-05-24 15:38 UTC
Labels: 🐞 Bug, ❌ Duplicate, P3: Normal, cat: client

**Comment by rayksland** [comment] 2020-05-24 17:55
Thank you, but I did compile. It works as I said above. ET is just pulling down a pk3 file that clobbers the working version.

**Comment by ensiform** [comment] 2020-05-24 18:11
It's pulling from the server you are trying to connect to. There is no way to change this until the server is also updated.

**Comment by isRyven** [comment] 2020-05-24 18:22
FWIW, this server is the only that works currently https://et.trackbase.net/server/45410/
