### ISSUE TITLE
Prestige/Skills random reset

### ISSUE THREAD

**Issue by rafal1137** [etlegacy/etlegacy#1619] opened 2021-03-14 20:08 UTC
Reported by Minimuppet on Discord:

> Is there any reason why it keeps resetting random peoples  happened again today. This isn't the first time either.
> 
> 2.77 legacy one of them
> another 2.76

**Comment by rmarquis** [comment] 2021-03-15 15:38
Are there more details to this issue? For now, I'm keen to assume a random removal/replacement of the etkey by random players leads to a random reset...

**Comment by Minimuppet** [comment] 2021-03-17 10:35
The only info i got from the players was the map finished and when the next map started there xp reset but it also reset their skill and gave them a prestige point. They didn't click to claim it.
Do you need anything else?

**Comment by rmarquis** [comment] 2021-03-17 12:27
So this is skills/prestige related, but not related to skill rating which is a different beast.

The only way to reset skills and acquire a prestige point is by clicking the button (which sends the `imcollectpr` command from the client side), so it indeed looks like that player inadvertently pressed the button.

In any case, the data doesn't seem to be "reset" or lost data, as the prestige point count is increased and the feature works correctly. Closing now, but feel free to reopen/comment in case you observe a big amount of similar cases, in which case joining server logs would help.

**Comment by Minimuppet** [comment] 2021-03-17 12:50
This just happen to 2 more people on server. is there anyway I can send you logs? is it just console log you want or do you need anything from the clients?

**Comment by rmarquis** [comment] 2021-03-17 13:29
Let's have a closer look. You can attach the related server log to comments here. If they exist, logs from clients might be useful too, but I am not sure what is recorded exactly.

Edit: I've identified a potential issue. I'll look into a fix shortly.

**Comment by ryzyk-krzysiek** [comment] 2021-03-17 15:03
I briefly checked the log and the code and tested it and I believe the problem is because `void G_LogExit(const char *string)` gets called twice and on the second time `level.intermissionQueued` is set, which means the prestige gets incremented and skills reset. 

https://github.com/etlegacy/etlegacy/blob/b35d249afcbcb77a0db6e64fbc941cb9ac7d5f42/src/game/g_main.c#L3753

https://github.com/etlegacy/etlegacy/blob/b35d249afcbcb77a0db6e64fbc941cb9ac7d5f42/src/game/g_prestige.c#L270-L294

You can see in the log `27119300 Exit: Wolf EndRound.` which calls `G_LogExit` for the first time and  again `27119300 Exit: Timelimit hit.`

Both calls seem to happend right after the other in `void CheckExitRules(void)` (`G_Script_ScriptEvent` and `G_LogExit("Timelimit hit.")`)

https://github.com/etlegacy/etlegacy/blob/b35d249afcbcb77a0db6e64fbc941cb9ac7d5f42/src/game/g_main.c#L4285-L4298

https://github.com/etlegacy/etlegacy/blob/b35d249afcbcb77a0db6e64fbc941cb9ac7d5f42/src/game/g_script_actions.c#L3860-L3870

So from the log it seems like normally only `Exit: Timelimit hit.` OR `Exit: Wolf EndRound.` gets called, but on this particular map `dingenskirchen_b8.pk3` both are. I did reproduce it on localhost on it. I checked 3 people and they got their prestige point claimed and 2 of them from the chat logs seemed like didn't try to.

Not sure why this would happen though, but maybe I'm wrong somewhere here or just missed something, I don't know that code too well.

EDIT: Removed log due to sensitive data.

**Comment by rmarquis** [comment] 2021-03-17 15:20
Good catch! I had the feeling something happened there, but I didn't realize the code was called twice in some case.
I'll try to figure out why this is called more than needed, but in any case I'll refactor the code so the reset part is completely independent from the streak count increase.

**Comment by Minimuppet** [comment] 2021-03-17 16:27
thanks for update, let me know if you need anything else

**Comment by rmarquis** [comment] 2021-04-03 16:16
A map ends either because an in-game action triggers the endround (`wm_endround` action script), or the time limit is reached.
In this case, the issue happens because the script of the dingenskirchen map triggers the action script when the time limit is reached, which indeed results in calling the G_LogExit function twice consecutively. 

```
trigger timelimit_hit
{
  wm_endround                                    <-- ??
  setstate suitcase_trans invisible
  // trigger world_clip show_officers
}
```

While the root of the issue is located in the map script, the code should be robust enough to avoid this case.
* A check has been added to ensure the exit condition is called only once, as to prevent the Ranks, Skill Rating, Prestige, and end of game statistics code to run twice with adverse effects
* Additionally, the Prestige code has been adjusted so the reset can only be done when the intermission is running, rather than simply queued.

**Closed as completed** 2021-04-15 15:12 UTC
Labels: 🐞 Bug, P4: Low, cat: mod QAGAME
